name: Проверки кода
on:
  push:
    branches: [ master ]
  pull_request:
    types: [ unlabeled, opened, synchronize, reopened, ready_for_review ]

jobs:
  checks:
    name: Проверки кода
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'WIP') == false && contains(github.event.pull_request.labels.*.name, 'Blocked') == false && contains(github.event.pull_request.labels.*.name, 'Suspended') == false

    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v2

      - name: Проверка code style
        run: yarn lint:ts
        if: always()
